name: pharma
description: "Pharma Alerte"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  go_router: ^12.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  aws_textract_api: ^2.0.0
  image_picker: ^1.0.0
  camera: ^0.10.0
  twilio_flutter: ^0.0.9
  flutter_svg: ^2.0.0
  google_fonts: ^4.0.4
  fl_chart: ^0.66.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  shimmer: ^3.0.0
  nb_utils: ^6.0.7
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"